# Generated by Django 2.2 on 2019-04-11 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(max_length=40)),
                ('Password', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40)),
                ('Phno', models.IntegerField()),
                ('DOB', models.IntegerField()),
                ('Adress', models.CharField(max_length=70)),
                ('Qualification', models.CharField(max_length=20)),
                ('Email', models.CharField(max_length=40)),
                ('Password', models.CharField(max_length=40)),
            ],
        ),
    ]
