# Generated by Django 2.2 on 2019-04-11 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('INTREST', models.CharField(max_length=40)),
                ('Hobbies', models.CharField(max_length=40)),
                ('Bio', models.CharField(max_length=90)),
            ],
        ),
    ]
