# Generated by Django 2.2 on 2019-04-12 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navu', '0003_usermodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login',
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='password',
            field=models.CharField(max_length=225),
        ),
    ]
