# Generated by Django 2.2 on 2019-04-18 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navu', '0004_auto_20190412_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='DOB',
            field=models.DateField(),
        ),
    ]
