# Generated by Django 2.2 on 2019-04-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navu', '0006_auto_20190418_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='Phno',
            field=models.BigIntegerField(),
        ),
    ]
