# Generated by Django 2.2 on 2019-04-21 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navu', '0007_auto_20190421_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('INTREST', models.CharField(max_length=255)),
                ('Hobbies', models.CharField(max_length=255)),
                ('Bio', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='bio',
        ),
    ]
